### ISSUE TITLE
mirror the repo to GCS

### ISSUE THREAD

**Issue by proppy** [hdl/conda-eda#183] opened 2022-02-24 06:07 UTC
It would be nice to mirror the repository to GCS by adding a https://conda.io/projects/conda-build/en/latest/resources/commands/conda-index.html step and https://github.com/google-github-actions/upload-cloud-storage to the current CI.

That would allow to work around the 3GB storage limitation of anaconda: https://docs.anaconda.com/anacondaorg/faq/#what-is-included-in-the-free-version-of-anaconda-org and allow for a more optimized serving path from GCP installing conda packages from managed notebooks or GCE vms startup scripts.

**Comment by mithro** [comment] 2022-05-18 16:14
I believe this is a duplicate of https://github.com/hdl/conda-eda/issues/204 ?

**Closed by mithro** 2022-05-18 16:14 UTC
Labels: duplicate
